/**
 * Analytics Dashboard Type Definitions
 *
 * This file contains all TypeScript interfaces and types used throughout
 * the Analytics Dashboard components for owner statement analytics.
 */

/**
 * Comparison type for analytics period comparisons
 */
export type ComparisonType = 'previous' | 'yoy' | 'custom';

/**
 * Granularity options for data aggregation
 */
export type GranularityType = 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';

/**
 * Configuration for analytics period and comparison settings
 */
export interface PeriodConfig {
  /** Start date of the primary analysis period */
  startDate: Date;

  /** End date of the primary analysis period */
  endDate: Date;

  /** Start date of the comparison period */
  compareStartDate: Date;

  /** End date of the comparison period */
  compareEndDate: Date;

  /** Data aggregation granularity level */
  granularity: GranularityType;

  /** Type of comparison being performed */
  comparisonType?: ComparisonType;
}

/**
 * Summary metrics with period-over-period comparison
 * Used for displaying key performance indicators with change indicators
 */
export interface AnalyticsSummary {
  /** Current period total revenue */
  currentRevenue: number;

  /** Previous/comparison period total revenue */
  previousRevenue: number;

  /** Percentage change in revenue (positive or negative) */
  revenueChange: number;

  /** Current period total expenses */
  currentExpenses: number;

  /** Previous/comparison period total expenses */
  previousExpenses: number;

  /** Percentage change in expenses (positive or negative) */
  expensesChange: number;

  /** Current period total payout amount */
  currentPayout: number;

  /** Previous/comparison period total payout amount */
  previousPayout: number;

  /** Percentage change in payout (positive or negative) */
  payoutChange: number;

  /** Current period total property management fees */
  currentPmFee: number;

  /** Previous/comparison period total property management fees */
  previousPmFee: number;

  /** Percentage change in PM fees (positive or negative) */
  pmFeeChange: number;

  /** Number of properties included in current period */
  propertyCount?: number;

  /** Number of statements processed in current period */
  statementCount?: number;
}

/**
 * Single data point for revenue trend visualization
 * Used in line/area charts to show trends over time
 */
export interface RevenueTrendPoint {
  /** Period identifier (e.g., "2024-01", "Week 1", "Q1 2024") */
  period: string;

  /** Timestamp for the period (used for x-axis positioning) */
  timestamp?: number;

  /** Total revenue for this period */
  revenue: number;

  /** Total expenses for this period */
  expenses: number;

  /** Total payout amount for this period */
  payout: number;

  /** Total property management fees for this period */
  pmFee?: number;

  /** Number of properties active in this period */
  propertyCount?: number;
}

/**
 * Expense category breakdown for donut/pie chart visualization
 * Represents a single expense category with its contribution
 */
export interface ExpenseCategory {
  /** Name of the expense category */
  category: string;

  /** Total amount for this category */
  amount: number;

  /** Percentage of total expenses (0-100) */
  percentage: number;

  /** Optional color for chart visualization */
  color?: string;

  /** Number of expense items in this category */
  itemCount?: number;

  /** Category identifier for grouping */
  categoryId?: string;
}

/**
 * Performance metrics for a single property
 * Used in property comparison tables and rankings
 */
export interface PropertyPerformance {
  /** Unique property identifier */
  propertyId: string;

  /** Property display name */
  name: string;

  /** Property address (optional) */
  address?: string;

  /** Total revenue generated by this property */
  revenue: number;

  /** Total payout amount for this property */
  payout: number;

  /** Total property management fees for this property */
  pmFee: number;

  /** Total expenses for this property */
  expenses: number;

  /** Net income (revenue - expenses - pmFee) */
  netIncome?: number;

  /** Profit margin percentage */
  profitMargin?: number;

  /** Number of nights booked (for vacation rentals) */
  nightsBooked?: number;

  /** Occupancy rate percentage (0-100) */
  occupancyRate?: number;

  /** Average daily rate */
  averageDailyRate?: number;

  /** Revenue per available night */
  revPAR?: number;

  /** Owner information */
  ownerId?: string;
  ownerName?: string;
}

/**
 * Filter options for analytics queries
 */
export interface AnalyticsFilters {
  /** Filter by specific property IDs */
  propertyIds?: string[];

  /** Filter by specific owner IDs */
  ownerIds?: string[];

  /** Filter by expense categories */
  expenseCategories?: string[];

  /** Minimum revenue threshold */
  minRevenue?: number;

  /** Maximum revenue threshold */
  maxRevenue?: number;

  /** Include only active properties */
  activeOnly?: boolean;
}

/**
 * Complete analytics data response structure
 * Returned from API calls to the analytics endpoints
 */
export interface AnalyticsData {
  /** Summary metrics with comparisons */
  summary: AnalyticsSummary;

  /** Revenue trend data points */
  revenueTrend: RevenueTrendPoint[];

  /** Expense category breakdown */
  expenseBreakdown: ExpenseCategory[];

  /** Property performance metrics */
  propertyPerformance: PropertyPerformance[];

  /** Period configuration used for this data */
  periodConfig: PeriodConfig;

  /** Applied filters */
  filters?: AnalyticsFilters;

  /** Timestamp when data was generated */
  generatedAt?: Date;
}

/**
 * Chart configuration options
 */
export interface ChartConfig {
  /** Show/hide legend */
  showLegend?: boolean;

  /** Show/hide grid lines */
  showGrid?: boolean;

  /** Enable/disable animations */
  animated?: boolean;

  /** Chart height in pixels */
  height?: number;

  /** Custom color scheme */
  colors?: string[];

  /** Number format (e.g., "$0,0.00") */
  numberFormat?: string;
}

/**
 * Export options for analytics data
 */
export interface ExportOptions {
  /** Export format */
  format: 'csv' | 'xlsx' | 'pdf' | 'json';

  /** Include charts in export */
  includeCharts?: boolean;

  /** Include raw data */
  includeRawData?: boolean;

  /** Custom filename */
  filename?: string;
}
