/**
 * Guard for suites that can only run against a POPULATED database.
 *
 * A few suites (statement accuracy, the analytics top-N checks) are data
 * regression tests: they re-run the production calculation logic over real
 * stored statements and assert the recomputed numbers still match. That only
 * means something with real data in the database — seeding fixtures would make
 * them tautological, since the fixtures would be generated by the same service
 * the test is meant to verify.
 *
 * So they declare the requirement instead of pretending to pass:
 *
 *   const describeWithData = requiresRealDatabase();
 *   describeWithData('analytics top 15', () => { ... });
 *
 * With a real DATABASE_URL the suite runs and asserts normally. Without one it
 * is reported as SKIPPED — visible in every `npm test` run with its name intact,
 * rather than silently filtered out of the run or, worse, green because every
 * assertion was short-circuited.
 *
 * The check is deliberately synchronous: Jest collects `describe` blocks before
 * any async hook can run, so the decision has to be made at module load.
 */

/**
 * True when the process is pointed at a database that could plausibly hold real
 * statement data — i.e. a non-SQLite DATABASE_URL. The local fallback is an
 * empty SQLite file, which never has any.
 */
function hasRealDatabase() {
    const url = process.env.DATABASE_URL;
    if (!url) return false;
    if (url.startsWith('sqlite')) return false;
    return true;
}

/**
 * Returns `describe` when a real database is configured, `describe.skip`
 * otherwise. Pass a label to make the skip reason obvious in the output.
 */
function requiresRealDatabase() {
    return hasRealDatabase() ? describe : describe.skip;
}

module.exports = { hasRealDatabase, requiresRealDatabase };
