const logger = require('../utils/logger');
const { Statement, Listing } = require('../models');
const { Op, fn, col } = require('sequelize');

class ScheduledReportService {
    /**
     * Generate a summary report for a date range.
     * Returns an object with key metrics.
     */
    async generateSummary(startDate, endDate) {
        const where = {
            weekStartDate: { [Op.lte]: endDate },
            weekEndDate: { [Op.gte]: startDate },
            propertyId: { [Op.ne]: null },
        };

        const [totals] = await Statement.findAll({
            attributes: [
                [fn('COUNT', col('id')), 'statementCount'],
                [fn('SUM', col('total_revenue')), 'totalRevenue'],
                [fn('SUM', col('pm_commission')), 'totalPmCommission'],
                [fn('SUM', col('owner_payout')), 'totalOwnerPayout'],
            ],
            where,
            raw: true,
        });

        const paidCount = await Statement.count({
            where: { ...where, payoutStatus: 'paid' },
        });

        const unpaidCount = await Statement.count({
            where: { ...where, payoutStatus: { [Op.or]: [null, 'failed'] } },
        });

        // Top 5 properties by revenue
        const topProperties = await Statement.findAll({
            attributes: [
                'propertyName',
                [fn('SUM', col('total_revenue')), 'revenue'],
            ],
            where,
            group: ['propertyName'],
            order: [[fn('SUM', col('total_revenue')), 'DESC']],
            limit: 5,
            raw: true,
        });

        return {
            period: { startDate, endDate },
            statementCount: parseInt(totals.statementCount) || 0,
            totalRevenue: parseFloat(totals.totalRevenue) || 0,
            totalPmCommission: parseFloat(totals.totalPmCommission) || 0,
            totalOwnerPayout: parseFloat(totals.totalOwnerPayout) || 0,
            paidCount,
            unpaidCount,
            topProperties: topProperties.map(p => ({
                name: p.propertyName,
                revenue: parseFloat(p.revenue) || 0,
            })),
        };
    }

    /**
     * Generate HTML email body for the summary report.
     */
    generateEmailHtml(summary) {
        const fmt = (n) => '$' + n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');

        return `<div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto">
            <div style="background:linear-gradient(135deg,#1e40af,#3b82f6);padding:24px;border-radius:12px 12px 0 0;color:white">
                <h1 style="margin:0;font-size:20px">Analytics Summary</h1>
                <p style="margin:4px 0 0;opacity:0.9">${summary.period.startDate} to ${summary.period.endDate}</p>
            </div>
            <div style="border:1px solid #e5e7eb;border-top:none;padding:24px;border-radius:0 0 12px 12px">
                <table style="width:100%;border-collapse:collapse">
                    <tr><td style="padding:8px 0;color:#6b7280">Statements</td><td style="padding:8px 0;text-align:right;font-weight:600">${summary.statementCount}</td></tr>
                    <tr><td style="padding:8px 0;color:#6b7280">Total Revenue</td><td style="padding:8px 0;text-align:right;font-weight:600;color:#059669">${fmt(summary.totalRevenue)}</td></tr>
                    <tr><td style="padding:8px 0;color:#6b7280">PM Commission</td><td style="padding:8px 0;text-align:right;font-weight:600">${fmt(summary.totalPmCommission)}</td></tr>
                    <tr><td style="padding:8px 0;color:#6b7280">Owner Payouts</td><td style="padding:8px 0;text-align:right;font-weight:600">${fmt(summary.totalOwnerPayout)}</td></tr>
                    <tr><td style="padding:8px 0;color:#6b7280">Paid</td><td style="padding:8px 0;text-align:right;font-weight:600;color:#059669">${summary.paidCount}</td></tr>
                    <tr><td style="padding:8px 0;color:#6b7280">Unpaid</td><td style="padding:8px 0;text-align:right;font-weight:600;color:#dc2626">${summary.unpaidCount}</td></tr>
                </table>
                ${summary.topProperties.length > 0 ? `
                <h3 style="margin:20px 0 8px;font-size:14px;color:#374151">Top Properties by Revenue</h3>
                <table style="width:100%;border-collapse:collapse">
                    ${summary.topProperties.map((p, i) => `<tr><td style="padding:4px 0;color:#6b7280">${i+1}. ${p.name}</td><td style="padding:4px 0;text-align:right;font-weight:600">${fmt(p.revenue)}</td></tr>`).join('')}
                </table>` : ''}
                <p style="margin:20px 0 0;font-size:12px;color:#9ca3af;text-align:center">Generated by Luxury Lodging PM</p>
            </div>
        </div>`;
    }

    /**
     * Send the summary report via email.
     */
    async sendReport(recipientEmail, startDate, endDate) {
        const summary = await this.generateSummary(startDate, endDate);
        const html = this.generateEmailHtml(summary);

        if (!process.env.SENDGRID_API_KEY) {
            logger.warn('Cannot send scheduled report: SENDGRID_API_KEY not set');
            return { sent: false, summary };
        }

        const sgMail = require('@sendgrid/mail');
        sgMail.setApiKey(process.env.SENDGRID_API_KEY);

        await sgMail.send({
            to: recipientEmail,
            from: process.env.SENDGRID_FROM_EMAIL || 'statements@luxurylodgingpm.com',
            subject: `Analytics Summary: ${startDate} to ${endDate}`,
            html,
        });

        logger.info('Scheduled report sent', { recipientEmail, startDate, endDate });
        return { sent: true, summary };
    }
}

module.exports = new ScheduledReportService();
